<?php 
return [
    'ACTION_TXF' => 1,
    'ACTION_BLINDTXF' => 2,
    'ACTION_TXTMSG' => 3,
    'ACTION_EMAIL' => 4,
    'ACTION_WEB' => 5,
    'ACTION_VMOFFER' => 6,
    'ACTION_HOLD' => 7,
    'ACTION_EMAIL_DELIVER' => 8,
    'ACTION_TEXT_DELIVER' => 9,
    'ACTION_DELIVER' => 10,
    'ACTION_LMR' => 11,
    'ACTION_DISPATCH' => 12,
    'ACTION_EMAIL_MINDER' => 13,
    'ACTION_TXTMSG_CONFIRM' => 33,
    'ACTION_EMAIL_CONFIRM' => 34,
    'ACTION_EMAIL_FORWARD' => 38,
    'ACTION_PROMPTS' => 30,
    'ACTION_LABEL' => 31,
    'ACTION_NONE' => 40,
    'ACTION_INFO' => 45,
    'ACTION_LEGACY' => 50,
    'ACTION_TXF_DELIVER' => 14,
    'ACTION_BLINDTXF_DELIVER' => 15,
    'ACTION_FAX' => 16,
    'ACTION_FAX_DELIVER' => 17,
    'ACTION_LMR_DELIVER' => 18,
    'ACTION_HOLDTIL' => 19,
    'ACTION_VM' => 20,
    'ACTION_VM_DELIVER' => 21,
    'ACTION_VMOFFER_DELIVER' => 22,
    'ACTION_TXF_NO_ANNOUNCEMENT' => 23,
    'ACTION_TXF_NO_ANNOUNCEMENT_DELIVER' => 24,
    'ACTION_CALENDAR' => 25,
    'ACTION_CALENDAR_DELIVER' => 26,
    'ACTION_DELIVER_LMR' => 27,
    'ACTION_WEBHOOK_DELIVER' => 32,
    'ACTION_PAGE' => 35,
    'ACTION_PAGE_DELIVER' => 36,
    'ACTION_DELIVER_IFCONFIRMED' => 28,
    'ACTION_STATUS_CHANGE' => 37,
    'ACTION_OFFSCRIPT' => 41,
    'ACTION_CRM' => 60,
    'ACTION_ONCALL' => 51,
    'ACTION_ONCALL_CONFIRM' => 52,
    'BREAK_REASON1' => 'Bathroom Break',
    'BREAK_REASON2' => 'Snack Break',
    'BREAK_REASON3' => 'Dispatching Duties',
    'BREAK_REASON4' => 'Lunch',
    'BREAK_REASON5' => 'Mentor Meeting',
    'BREAK_REASON6' => 'Staff Meeting',
    'BREAK_REASON7' => 'Start of Shift',
    'BREAK_REASON8' => 'End of Shift',
    'BREAK_REASON9' => 'Technical Issue',
    'BREAK_REASON10' => 'Training',
    'BREAK_REASON11' => 'Other',
    'BREAK_REASON12' => 'EVP',
    'EVENT_TEXT' => 1,
    'EVENT_BTNCLICK' => 2,
    'EVENT_MINDERCLICK' => 3,
    'EVENT_MSGEDITED' => 4,
    'EVENT_DELIVER' => 5,
    'EVENT_UNDELIVER' => 6,
    'EVENT_MINDER' => 7,
    'EVENT_UNMINDER' => 8,
    'EVENT_CALLSTART' => 10,
    'EVENT_CALLEND' => 11,
    'EVENT_TRANSFER' => 12,
    'EVENT_DELIVERY' => 13,
    'EVENT_HANGUP' => 14,
    'EVENT_ADMIN' => 15,
    'EVENT_CUSTOM' => 16,
    'EVENT_ACTIONCLICK' => 17,
    'EVENT_DIALOUT' => 18,
    'EVENT_PATCH' => 19,
    'EVENT_HOLD' => 21,
    'EVENT_UNHOLD' => 22,
    'EVENT_FILL_PROMPT' => 23,
    'EVENT_CALLTYPE' => 24,
    'EVENT_AUDIT' => 25,
    'EVENT_CALENDAR' => 26,
    'EVENT_REPOP' => 27,
    'EVENT_MSGVIEW' => 28,
    'EVENT_TRANSFER_RESULT' => 29,
    'EVENT_LEAD' => 30,
    'EVENT_CANCEL' => 31,
    'EVENT_DIALOUT_OVERRIDE' => 32,
    'EVENT_SECURITY' => 101,
    'EVENT_REPEATCALLER' => 33,
    'EVENT_OFFSCRIPT' => 34,
    'EVENT_OTHER' => 99,
    'EVENT_DEBUG' => 100,
    'USEREVT_LOGIN' => 1,
    'USEREVT_LOGOUT' => 2,
    'USEREVT_BREAK' => 3,
    'USEREVT_START_SHIFT' => 4,
    'USEREVT_END_SHIFT' => 5,
    'USEREVT_TAKING_CALLS' => 6,
    'USEREVT_NOT_TAKING_CALLS' => 7,
    'USEREVT_LEAVE_BREAK' => 8,
    'USEREVT_NOT_TAKING_CALLS_BTN' => 9,
    'USEREVT_TAKING_CALLS_BTN' => 10,
    'USEREVT_REFRESH_BROWSER' => 11,
    'USEREVT_OA_PAGE_LOAD' => 12,
    'USEREVT_TWILIO' => 13,
    'USEREVT_MISC' => 99,
    'CONTACT_PHONE' => 'Phone',
    'CONTACT_CELL' => 'Cell',
    'CONTACT_EMAIL' => 'Email',
    'CONTACT_VMAIL' => 'Vmail',
    'CONTACT_TEXT' => 'Text',
    'CONTACT_WEB' => 'Webform',
    'CONTACT_LMR' => 'LMR',
    'CONTACT_CALENDAR' => 'Calendar',
    'CONTACT_FAX' => 'Fax',
    'BUTTON_DISPATCH' => 'Dispatch',
    'BUTTON_UNDISPATCH' => 'Undispatch',
    'BUTTON_DELIVER' => 'Deliver',
    'BUTTON_DELIVER_LMR' => 'Deliver by LMR',
    'BUTTON_OFFSCRIPT' => 'Offscript',
    'EVT_LVL_CUSTOMER' => 1,
    'EVT_LVL_OPERATOR' => 10,
    'EVT_LVL_MANAGER' => 20,
    'EVT_LVL_ADMIN' => 30,
    'EVT_LVL_SUPERUSER' => 40,
    'FAX_EMAIL' => '',
    'PROMPT_NAME' => 'First and Last Name',
    'PROMPT_MISC' => 'Misc',
    'PROMPT_PHONE' => 'Phone Number',
    'PROMPT_TYPE_SINGLELINE' => 1,
    'PROMPT_TYPE_MULTILINE' => 2,
    'PROMPT_TYPE_DROPDOWN' => 3,
    'PROMPT_TYPE_STRICTDROPDOWN' => 5,
    'PROMPT_TYPE_DBLOOKUP' => 6,
    'MSG_EMAIL_SUBJECT' => 'Answering Service Message',
    'EMPLOYEE_TYPE_EMPLOYEE' => 'Employee',
    'EMPLOYEE_TYPE_GENERIC_CONTACT' => 'Generic Contact',
    'security_questions' => [
        'Pin Number' => 'Pin Number',
        'Last 4 of SSN' => 'Last 4 of SSN',
        'What city were you born in?' => 'What city were you born in?',
    ],
    'email_format' => [
        '0' => 'html',
        '1' => 'text',
    ],
    'smtp_profiles' => [
        'default' => 'Not Secure',
        'secure_only' => 'Secure Only',
        'dexyp' => 'DexYP',
    ],
    'icons' => [
        'welcome' => 'fa-home',
        'accounts' => 'fa-bars',
        'setup' => 'fa-cogs',
        'reports' => 'fa-bar-chart',
        'calls' => 'fa-list',
        'messages' => 'fa-envelope',
        'inbox' => 'fa-envelope',
        'complaints' => 'fa-thumbs-down',
        'mistakes' => 'fa-frown',
        'bulletins' => 'fa-thumb-tack',
        'campaigns' => 'fa-share-square',
        'users' => 'fa-user',
        'roles' => 'fa-users',
        'settings' => 'fa-wrench',
        'logout' => 'fa-power-off',
    ],
    'contact_types' => [
        'CONTACT_PHONE' => 'Phone',
        'CONTACT_CELL' => 'Cell',
        'CONTACT_EMAIL' => 'Email',
        'CONTACT_VMAIL' => 'Vmail',
        'CONTACT_TEXT' => 'Text',
        'CONTACT_FAX' => 'Fax',
        'CONTACT_WEB' => 'Webform',
        'CONTACT_LMR' => 'LMR',
        'CONTACT_CALENDAR' => 'Calendar',
    ],
    'actions' => [
        'ACTION_LEGACY' => ['label' => '', 'need_eid' => false, 'show' => false, 'type' => 'ACTION_LEGACY'],
        'ACTION_PROMPTS' => ['label' => '', 'need_eid' => false, 'show' => false, 'type' => 'ACTION_PROMPTS'],
        'ACTION_NONE' => ['label' => '', 'need_eid' => false, 'show' => false, 'type' => 'ACTION_NONE'],
        'ACTION_INFO' => ['label' => '', 'need_eid' => false, 'show' => false, 'type' => 'ACTION_INFO'],
        'ACTION_TXF' => [
            'action_label' => 'Transfer', 'label' => 'Transfer to', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_TXF'],
        'ACTION_TXF_DELIVER' => ['action_label' => 'Transfer', 'label' => 'Transfer (and DELIVER) to', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_TXF_DELIVER'],
        'ACTION_BLINDTXF' => ['action_label' => 'Transfer', 'label' => 'Blind Transfer to', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_BLINDTXF'],
        'ACTION_BLINDTXF_DELIVER' => ['action_label' => 'Transfer', 'label' => 'Blind Transfer to (and DELIVER)', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_BLINDTXF_DELIVER'],
        'ACTION_EMAIL' => ['action_label' => 'Email', 'label' => 'Email', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_EMAIL'],
        'ACTION_EMAIL_CONFIRM' => ['action_label' => 'Email (with CONFIRMATION)', 'label' => 'Email (with CONFIRMATION)', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_EMAIL_CONFIRM'],
        'ACTION_EMAIL_DELIVER' => ['action_label' => 'Email', 'label' => 'Email (and DELIVER)', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_EMAIL_DELIVER'],
        'ACTION_EMAIL_FORWARD' => ['action_label' => 'Email (w/org email)', 'label' => 'Email (w/org email)', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_EMAIL_FORWARD'],
        'ACTION_PAGE' => ['action_label' => 'Page', 'label' => 'Page', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_PAGE'],
        'ACTION_PAGE_DELIVER' => ['action_label' => 'Page', 'label' => 'Page (and DELIVER)', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_PAGE_DELIVER'],
        'ACTION_VMOFFER' => ['label' => 'Offer voicemail of', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_VMOFFER'],
        'ACTION_VMOFFER_DELIVER' => ['label' => 'Offer voicemail of (AND DELIVER)', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_VMOFFER_DELIVER'],
        'ACTION_VM' => ['action_label' => 'Voicemail', 'label' => 'Send to voicemail of', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_VM'],
        'ACTION_VM_DELIVER' => ['action_label' => 'Transfer', 'label' => 'Send to voicemail of (and DELIVER)', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_VM_DELIVER'],
        'ACTION_HOLD' => ['action_label' => 'Save and Hold', 'label' => 'Save & Hold', 'need_eid' => false, 'show' => true, 'type' => 'ACTION_HOLD'],
        'ACTION_HOLDTIL' => ['action_label' => 'Hold Until', 'label' => 'Hold Til', 'need_eid' => false, 'show' => true, 'type' => 'ACTION_HOLDTIL'],
        'ACTION_TXTMSG' => ['action_label' => 'Text', 'label' => 'Text to', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_TXTMSG'],
        'ACTION_TXTMSG_CONFIRM' => ['action_label' => 'Text (with CONFIRMATION)', 'label' => 'Text (with CONFIRMATION) to', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_TXTMSG_CONFIRM'],
        'ACTION_TEXT_DELIVER' => ['action_label' => 'Text', 'label' => 'Text (and DELIVER) to', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_TEXT_DELIVER'],
        'ACTION_DELIVER' => ['label' => 'Mark as DELIVERED', 'need_eid' => false, 'show' => true, 'type' => 'ACTION_DELIVER'],
        'ACTION_DELIVER_LMR' => ['label' => 'Mark as DELIVERED BY LMR', 'need_eid' => false, 'show' => true, 'type' => 'ACTION_DELIVER_LMR'],
        'ACTION_DELIVER_IFCONFIRMED' => ['label' => 'Mark as DELIVERED if CONFIRMED', 'need_eid' => false, 'show' => true, 'type' => 'ACTION_DELIVER_IFCONFIRMED'],
        'ACTION_LMR' => ['action_label' => 'LMR', 'label' => 'LMR to', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_LMR'],
        'ACTION_LMR_DELIVER' => ['action_label' => 'LMR', 'label' => 'LMR to (and DELIVER)', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_LMR_DELIVER'],
        'ACTION_DISPATCH' => ['label' => 'Send to DISPATCH', 'need_eid' => false, 'show' => true, 'type' => 'ACTION_DISPATCH'],
        'ACTION_WEB' => ['action_label' => 'Web form', 'label' => 'Fill web form', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_WEB'],
        'ACTION_FAX' => ['action_label' => 'Fax', 'label' => 'Fax', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_FAX'],
        'ACTION_FAX_DELIVER' => ['action_label' => 'Fax', 'label' => 'Fax (and DELIVER)', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_FAX_DELIVER'],
        'ACTION_CALENDAR' => ['label' => 'Schedule appointment for', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_CALENDAR'],
        'ACTION_CRM' => ['action_label' => 'Contacts', 'label' => 'CRM', 'need_eid' => false, 'show' => true, 'type' => 'ACTION_CRM'],
        'ACTION_WEBHOOK_DELIVER' => ['action_label' => 'Post to URL and DELIVER', 'label' => 'Post to URL (and DELIVER)', 'need_eid' => false, 'show' => true, 'type' => 'ACTION_WEBHOOK_DELIVER'],
        'ACTION_STATUS_CHANGE' => ['action_label' => 'Change Status', 'label' => 'Change Status', 'need_eid' => false, 'show' => true, 'type' => 'ACTION_STATUS_CHANGE'],
        'ACTION_OFFSCRIPT' => ['action_label' => 'Deliver Offscript Message', 'label' => 'Deliver Offscript Message', 'need_eid' => false, 'show' => true, 'type' => 'ACTION_OFFSCRIPT'],
        'ACTION_ONCALL' => ['action_label' => 'Contact On-call', 'label' => 'Contact On-call', 'need_eid' => false, 'show' => true, 'type' => 'ACTION_ONCALL'],
        'ACTION_ONCALL_CONFIRM' => ['action_label' => 'Contact On-call (with CONFIRMATION)', 'label' => 'Contact On-call (with CONFIRMATION)', 'need_eid' => false, 'show' => true, 'type' => 'ACTION_ONCALL_CONFIRM'],
    ],
    'actions_customers' => [
        'ACTION_LEGACY' => ['label' => '', 'need_eid' => false, 'show' => false, 'type' => 'ACTION_LEGACY'],
        'ACTION_PROMPTS' => ['label' => '', 'need_eid' => false, 'show' => false, 'type' => 'ACTION_PROMPTS'],
        'ACTION_NONE' => ['label' => '', 'need_eid' => false, 'show' => false, 'type' => 'ACTION_NONE'],
        'ACTION_INFO' => ['label' => '', 'need_eid' => false, 'show' => false, 'type' => 'ACTION_INFO'],
        'ACTION_TXF' => ['label' => 'Transfer the call to to', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_TXF'],
        'ACTION_TXF_DELIVER' => ['label' => 'Transfer the call to', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_TXF_DELIVER'],
        'ACTION_BLINDTXF' => ['label' => 'Blind transfer to', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_BLINDTXF'],
        'ACTION_BLINDTXF_DELIVER' => ['label' => 'Blind transfer the call to', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_BLINDTXF_DELIVER'],
        'ACTION_EMAIL' => ['label' => 'Email', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_EMAIL'],
        'ACTION_EMAIL_DELIVER' => ['label' => 'Email caller info to ', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_EMAIL_DELIVER'],
        'ACTION_VMOFFER' => ['label' => 'Offer voicemail of', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_VMOFFER'],
        'ACTION_VM' => ['label' => 'Send to voicemail of', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_VM'],
        'ACTION_VM_DELIVER' => ['label' => 'Send to voicemail of (and DELIVER)', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_VM_DELIVER'],
        'ACTION_HOLD' => ['label' => 'Save & Hold', 'need_eid' => false, 'show' => true, 'type' => 'ACTION_HOLD'],
        'ACTION_TXTMSG' => ['label' => 'Text caller info to', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_TXTMSG'],
        'ACTION_TEXT_DELIVER' => ['label' => 'Text caller info to', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_TEXT_DELIVER'],
        'ACTION_DELIVER' => ['label' => 'Mark as DELIVERED', 'need_eid' => false, 'show' => true, 'type' => 'ACTION_DELIVER'],
        'ACTION_LMR' => ['label' => 'LMR to', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_LMR'],
        'ACTION_LMR_DELIVER' => ['label' => 'Live message relay to', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_LMR_DELIVER'],
        'ACTION_DISPATCH' => ['label' => 'Send to DISPATCH', 'need_eid' => false, 'show' => true, 'type' => 'ACTION_DISPATCH'],
        'ACTION_WEB' => ['label' => 'Fill web form', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_WEB'],
        'ACTION_FAX' => ['label' => 'Fax', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_FAX'],
        'ACTION_FAX_DELIVER' => ['label' => 'Fax caller info to', 'need_eid' => true, 'show' => true, 'type' => 'ACTION_FAX_DELIVER'],
    ],
    'privacy' => [
        '1' => 'Public',
        '2' => 'Private'
    ],
    'type' => [
        '1' => 'Virtual Receptionist',
        '2' => 'Answering Service'
    ],
    'difficulty' => [
        '1' => '1', '2' => '2', '3' => '3', '4' => '4', '5' => '5', '6' => '6', '7' => '7', '8' => '8', '9' => '9', '10' => '10', '11' => '11', '12' => '12', '13' => '13', '14' => '14', '15' => '15', '16' => '16', '17' => '17', '18' => '18', '19' => '19', '20' => '20'
    ],
];