const PROMPT_TYPE_SINGLELINE = 1;
const PROMPT_TYPE_MULTILINE = 2;
const PROMPT_TYPE_DROPDOWN = 3;
const PROMPT_TYPE_STRICTDROPDOWN = 4;
const PROMPT_TYPE_DBLOOKUP = 5;
const PROMPT_TYPE_CONDITIONAL = 6;

const ACTION_LEGACY = 0;
const ACTION_TXF = 1;
const ACTION_BLINDTXF = 2;
const ACTION_TXTMSG = 3;
const ACTION_EMAIL = 4;
const ACTION_WEB = 5;
const ACTION_VMOFFER = 6;
const ACTION_HOLD = 7;
const ACTION_EMAIL_DELIVER = 8;
const ACTION_TEXT_DELIVER = 9;
const ACTION_DELIVER = 10;
const ACTION_LMR = 11;
const ACTION_DISPATCH = 12;
const ACTION_EMAIL_MINDER = 13;
const ACTION_TXF_DELIVER = 14;
const ACTION_BLINDTXF_DELIVER = 15;
const ACTION_FAX = 16;
const ACTION_FAX_DELIVER = 17;
const ACTION_LMR_DELIVER = 18;
const ACTION_HOLDTIL = 19;
const ACTION_VM = 20;
const ACTION_VM_DELIVER = 21;
const ACTION_VMOFFER_DELIVER = 22;
const ACTION_TXF_NO_ANNOUNCEMENT = 23;
const ACTION_TXF_NO_ANNOUNCEMENT_DELIVER = 24;
const ACTION_CALENDAR = 25;
const ACTION_CALENDAR_DELIVER = 26;
const ACTION_DELIVER_LMR = 27;
const ACTION_WEBHOOK_DELIVER = 32;
const ACTION_PAGE = 35;
const ACTION_PAGE_DELIVER = 36;
const ACTION_DELIVER_IFCONFIRMED = 28;
const ACTION_STATUS_CHANGE = 37;
const ACTION_OFFSCRIPT = 41;
const ACTION_INFO = 45;
const ACTION_NONE = 40;

const CONTACT_PHONE = 1;

export {
    PROMPT_TYPE_SINGLELINE,
    PROMPT_TYPE_MULTILINE,
    PROMPT_TYPE_DROPDOWN,
    PROMPT_TYPE_STRICTDROPDOWN,
    PROMPT_TYPE_DBLOOKUP,
    PROMPT_TYPE_CONDITIONAL,
    ACTION_LEGACY,
    ACTION_TXF,
    ACTION_BLINDTXF,
    ACTION_TXTMSG,
    ACTION_EMAIL,
    ACTION_WEB,
    ACTION_VMOFFER,
    ACTION_HOLD,
    ACTION_EMAIL_DELIVER,
    ACTION_TEXT_DELIVER,
    ACTION_DELIVER,
    ACTION_LMR,
    ACTION_DISPATCH,
    ACTION_EMAIL_MINDER,
    ACTION_TXF_DELIVER,
    ACTION_BLINDTXF_DELIVER,
    ACTION_FAX,
    ACTION_FAX_DELIVER,
    ACTION_LMR_DELIVER,
    ACTION_HOLDTIL,
    ACTION_VM,
    ACTION_VM_DELIVER,
    ACTION_VMOFFER_DELIVER,
    ACTION_TXF_NO_ANNOUNCEMENT,
    ACTION_TXF_NO_ANNOUNCEMENT_DELIVER,
    ACTION_CALENDAR,
    ACTION_CALENDAR_DELIVER,
    ACTION_DELIVER_LMR,
    ACTION_WEBHOOK_DELIVER,
    ACTION_PAGE,
    ACTION_PAGE_DELIVER,
    ACTION_DELIVER_IFCONFIRMED,
    ACTION_STATUS_CHANGE,
    ACTION_OFFSCRIPT,
    ACTION_INFO,
    ACTION_NONE,
    CONTACT_PHONE,
};